config/routes.rb
require 'sidekiq/web'
Rich::Application.routes.draw do

  get "redirect_settings/show"
  get "redirect_settings/update"
  get "redirect_settings/destroy"
  devise_for :dealers , controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }

  constraints subdomain: 'api' do
    scope module: 'api' do
      get "/apps_advert/:provider" => "seller_api#apps_advert"
      get "/welcome/:id.js"        => 'script#welcome'
      get "/thankyou/:id.js"       => 'script#thankyou'
      get "/confirm/:id.js"        => 'script#confirm'
      get '/'                      => 'api#property'
    end
  end

  userapi_domain = if Rails.env.production?
    'richpays.com'
  else
    'rich.dev'
  end
  constraints domain: userapi_domain, subdomain: 'userapi' do
    scope module: 'dealer_api' do
      get '/'                             => 'application#property'
      get  'offers'                       => 'offers#index', :defaults => { :format => :json }
      get  'offers/:id'                   => 'offers#show', :defaults => { :format => :json }
      get  'campaigns'                    => 'campaigns#index', :defaults => { :format => :json }
      get  'campaigns/:id'                => 'campaigns#show', :defaults => { :format => :json }
      post 'campaigns/:id/mass_offer_set' => 'campaigns#mass_offer_set', :defaults => { :format => :json }
      post 'campaigns/:id/set_all_offers' => 'campaigns#set_all_offers', :defaults => { :format => :json }
    end
  end

unless Rails.env.development?
    constraints domain: 'richpays.net' do
      get  '/robots.txt' => 'home#robots'
    end
  end

  unless Rails.env.development?
    constraints domain: 'apst.me' do
      get  '/'                            => 'home#property'
      scope module: 'api' do
        get  '/agreement'                 => 'landing_subscribers#agreement'
        get  '/unsubscribe'               => 'landing_subscribers#unsubscribe'
        post '/unsubscribe'               => 'landing_subscribers#sms_unsubscribe'
        get  "/:code"                     => 'buyer_session#handler'
        get  "/:code/:anything"           => 'buyer_session#handler'
        post "/:code/send-link"           => 'landing_subscribers#sms_subscribe'
        post "/:code/:anything/send-link" => 'landing_subscribers#sms_subscribe'
        get  '/robots.txt'                => 'api#robots'
        get  '/'                          => 'api#property'
      end
    end
    [ ['itunes', 'apple-com.info' ], [ 'play', 'google-com.me' ] ].each do | subdomain, domain |
      constraints domain: domain, subdomain: subdomain do
        scope module: 'api' do
          get  '/agreement'         => 'landing_subscribers#agreement'
          get  '/unsubscribe'       => 'landing_subscribers#unsubscribe'
          post '/unsubscribe'       => 'landing_subscribers#sms_unsubscribe'
          get  '/:code'             => 'buyer_session#handler'
          get  '/:code/:anything'   => 'buyer_session#handler'
          post "/:code/send-link"   => 'landing_subscribers#sms_subscribe'
          get  '/robots.txt'        => 'api#robots'
          get  '/'                  => 'api#property'
        end
      end
    end
  end

    scope module: :personal do
      resources :faqs
      resources :news
      resources :money
      resources :wallets
      resources :referrers
      resources :notifications
      resources :money_options
      resources :dealer_balance
      resources :requests_history
      resources :countries, only: [ :index ]
      resources :offers, only: [ :index, :show ]
      resources :direct_offers, only: [ :index, :show, :create, :update ], param: :hashid
      get 'offers/:id/countries' => 'offers#countries'
      resources :offer_sets, only: [ :show, :new, :create, :update ]
      resources :payment_requests, only: [ :new, :create ]

      match :current_dealer, to: 'settings#show',   via: :get
      match :current_dealer, to: 'settings#update', via: :put
      get   :sidebar,        to: 'sidebar_notifications#show'

      get 'settings/phone_update', to: 'settings#request_confirmation_code'

      resources :dashboard
      match 'dashboard_campaigns',      to: 'dashboard#campaigns',              via: :get
      match 'dashboard_actions',        to: 'dashboard#conversions',            via: :get
      match 'dashboard_offers',         to: 'dashboard#offers',                 via: :get
      match 'dashboard_offers/:id',     to: 'dashboard#offer',                  via: :get
      match 'dashboard_create_request', to: 'dashboard#create_payment_request', via: :post
      match 'dashboard',                to: 'dashboard#index',                  via: :get

      match 'stats/table',           to: 'dealer_stats#table',           via: :get, as: :table_dealer_stats,           :defaults => { :format => :json }
      match 'stats/dashboard_graph', to: 'dealer_stats#dashboard_graph', via: :get, as: :dashboard_graph_dealer_stats, :defaults => { :format => :json }
      match 'stats/conversions',     to: 'dealer_stats#conversion',      via: :get, as: :conversion_dealer_stats,      :defaults => { :format => :json }
      get   'stats/subscribes',      to: 'dealer_stats#subscribes'

      resources :tickets
      match 'tickets/:id/ticket_messages', to: 'tickets#ticket_messages', via: :get, as: :ticket_messages, :defaults => { :format => :json }

      resources :campaigns
      get   'campaigns_light',              to: 'campaigns#light_index'
      get   'campaigns/:id/weblanding',     to: 'campaigns#weblanding'
      get   'campaigns/:id/check_pdf',      to: 'campaigns#check_pdf'
    end

    namespace :admin do
      get '/'       => 'dashboard#index',    as: :index, via: [ :get, :post ]
      get 'login'   => 'session#new',        as: :login
      post 'login'  => 'session#admin_auth', as: :auth
      post 'resend' => 'session#resend',     as: :resend
      post 'renew'  => 'session#renew',      as: :renew
      get 'logout'  => 'session#destroy',    as: :logout

      resources :sellers, as: :sellers do
        get :common_stats, as: :common_stats
        get :recent_stats, as: :recent_stats, via: [ :get, :post ]
      end

      resources :dealer_stats, only: [ :index ], defaults: { format: :json }
      resources :timing_stats, only: [ :index ], defaults: { format: :json }
      get 'dealer_stats/top_cr', to: 'dealer_stats#top_cr', defaults: { format: :json }

      get  'dealers_list',        to: 'dealers#dealers_list',      defaults: { format: :json }
      post 'dealer_mailings',     to: 'dealer_emails#send_emails', defaults: { format: :json }
      get  'dealer_mailings',     to: 'dealer_emails#index',       defaults: { format: :json }
      get  'dealer_mailings/:id', to: 'dealer_emails#show',        defaults: { format: :json }
      get  'dealers/get_scope',   to: 'dealers#get_scope',         defaults: { format: :json }

      get 'cached_dealers', to: 'dealers#cached', defaults: { format: :json }
      get 'cached_offers', to: 'offers#cached', defaults: { format: :json }

      resources :admin_requests, only: [ :index, :create ]

      resources :dealers, as: :dealers do
        post :change_balance, as: :change_balance
        get  :become, as: :become
      end

      get :requests_for_dealer, to: 'dealers#requests', defaults: { format: :json }

      resources :direct_offers, only: [ :index, :create, :update ]

      resources :payments
      post 'payments/:id/as_csv', to: 'payments#as_csv'
      resources :payment_requests

      resources :offers, as: :offers do
        get :disable, as: :disable, to: 'offers#disable'
      end

      resources :tickets, as: :tickets
      match 'tickets/:id/ticket_messages', to: 'tickets#ticket_messages', via: :get, as: :ticket_messages, :defaults => { :format => :json }
      resources :news, as: :news
      resources :faqs, as: :faqs
      resources :offer_icons, only: [ :create ]
      resources :offer_screenshots, only: [ :create, :destroy ]
      post :mass_offer_switch, to: 'offers#mass_switch'

      get :affilate_offer, as: :affilate_offer, to: 'affilate_offer#show'
    end


  post :support, to: 'home#support'
  authenticate :dealer, lambda { |u| u.is_an_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :notification_settings, only: [:show, :update]

  if Rails.env.test? or Rails.env.development?
    scope module: 'api' do
      get  "/s/:id"                         => 'buyer_session#handler'
      get  "/w/:id"                         => 'buyer_session#wapclick'
      get  "/c/:id"                         => 'buyer_session#create'
      get  "/o/:id"                         => 'direct_offer#show',  constraints: { subdomain: 'target' }
      get  "/o/:id"                         => 'buyer_session#show'
      get  "/t/:id"                         => 'buyer_session#tb'
      get  "/k/:id"                         => 'buyer_session#clicker'
    end
  end

  api_domains = if Rails.env.development?
    %w( api5.dev api9.dev mobile333.dev )
  else
    %w( api5.net api9.net mobile333.com xeclick.com dorovsky.com )
  end
  api_domains.each do | api_domain |
    constraints domain: api_domain do
      get  '/'                                => 'home#index', constraints: { domain: 'dorovsky.com' }
      scope module: 'api' do
        get "/apps_advert/:provider"          => "seller_api#apps_advert"
        get  "/s/:id"                         => 'buyer_session#handler'
        get  "/w/:id"                         => 'buyer_session#wapclick'
        post "/s/:id"                         => 'api#http_200_ok'
        get  "/c/:id"                         => 'buyer_session#create'
        get  "/o/:id"                         => 'buyer_session#target_show', constraints: { subdomain: 'target' }
        get  "/o/:id"                         => 'buyer_session#show'
        get  "/t/:id"                         => 'buyer_session#tb'

app/models/seller.rb
class Seller < ActiveRecord::Base

  has_many :offers
  has_many :offer_sets
  has_many :campaigns
  has_one :seller_balance
  has_many :seller_increments

  before_save  :set_provider_system_name
  after_create :new_balance

  validates_presence_of :seller_name

  scope :active,       -> { where( active: true ) }
  scope :apps_advert,  -> { where( kind: [ 'apps_advert', 'cpa' ] ) }
  scope :cpa,          -> { where( kind: 'apps_advert' ) }
  scope :wapclick,     -> { where( kind: 'wapclick' ) }

  def self.system_provider
    seller = find_by( kind: 'system' )
    unless seller
      seller = new
      seller.kind                 = 'system'
      seller.seller_name          = 'system_seller' 
      seller.provider_system_name = 'system'
      seller.prefix               = 'system'
      active                      = false
      seller.save
    end
    seller
  end

  def new_balance
    SellerBalance.create( seller_id: self.id )
  end

  def increase_balance( value, type = nil )
    type ||= "confirmed"
    seller_balance.increase( value, type )
    SellerIncrement.increase( self, value, type )
  end

  def decrease_balance( value, type = nil )
    type ||= "confirmed"
    seller_balance.decrease( value, type )
    SellerIncrement.decrease( self, value, type )
  end

  def recent_stats( options={} )
    now = Time.zone.now
    day = options[ :per ] ? Time.parse( options[ :per ] ) : now
    day_range = day.beginning_of_day..day.end_of_day
    seller_increments.where( created_at: day_range ).order( :created_at )
  end

  def set_provider_system_name
    self.provider_system_name = seller_name.downcase
  end

end

app/controllers/admin/sellers_controller.rb
class Admin::SellersController < Admin::MainController

  before_filter :admin_required
  layout 'admin/layouts/logged_in'

  def new
    @seller = Seller.new 
    @offers = @seller.offers
  end

  def create
    @seller = Seller.new( seller_params )
    if @seller.save
      redirect_to admin_sellers_path
    else
      render action: 'new'
    end
  end

  def index
    @sellers = Seller.active
  end

  def show
    @seller = Seller.find( params[ :id ] )
    @offers = @seller.offers
  end

  def edit
    @seller = Seller.find( params[ :id ] )
  end

  def update
    @seller = Seller.find( params[ :id ] )
    if @seller.update_attributes( seller_params )
      redirect_to admin_seller_path
    else
      render action: 'edit'
    end
  end

  def destroy
  end

  def common_stats
    @seller = Seller.find( params[ :admin_seller_id ] )
    @balance = @seller.seller_balance    
  end

  def recent_stats
    @seller = Seller.find( params[ :admin_seller_id ] )
    @stats = @seller.recent_stats( per: params[ :start_date ] )
  end

  def date_converter( date )
    datetime = "#{date["day"]}-#{date["month"]}-#{date["year"]} #{date["hour"]}:#{date["minute"]}".to_time
  end

  private

  def seller_params
    params.fetch( :seller, {} ).permit( :seller_name, :seller_url, :contact_name, :contact_phone, :contact_email, :active )
  end

end

app/views/admin/sellers/_seller_edit_form.html.slim
.large-6
  = form_for @seller, url: {action: "update"} do |f|
      = f.label "Имя рекламодателя"
      = f.text_field :seller_name
      = f.label "Страница рекламоодателя"
      = f.text_field :seller_url
      = f.label "Контактное лицо"
      = f.text_field :contact_name
      = f.label "Контактный телефон"
      = f.text_field :contact_phone
      = f.label "Контактный email"
      = f.text_field :contact_email
      = f.label "Активация рекламодателя"   
      = f.radio_button( "active", "true", checked: @seller.active == true )
      span' Активен
      = f.radio_button( "active", "false", checked: @seller.active == false )
      span' Неактивен
      = f.submit "Сохранить", class: 'button'

app/views/admin/sellers/_seller_new_form.html.slim
.large-6
  = form_for @seller, url: {action: "create"} do |f|
      = f.label "Имя рекламодателя"
      = f.text_field :seller_name
      = f.label "Страница рекламоодателя"
      = f.text_field :seller_url
      = f.label "Контактное лицо"
      = f.text_field :contact_name
      = f.label "Контактный телефон"
      = f.text_field :contact_phone
      = f.label "Контактный email"
      = f.text_field :contact_email
      = f.label "Активация рекламодателя"   
      input#activeTrue name="seller[active]" type="radio" value="true" 
        label for="activeTrue" Включить
      input#activeFalse name="seller[active]" type="radio" value="false" 
        label for="activeFalse" Выключить
      = f.submit "Сохранить", class: 'button'

app/views/admin/sellers/common_stats.html.slim
= link_to @seller.seller_name, admin_seller_path( @seller ), class: 'button'

table
  thead
    tr
      th Ожидает начисления
      th Начислено
      th Переходов
      th Подписок
      th Ребиллов
      th Отписок
  tbody
    tr
      td #{@balance.waiting} руб.
      td #{@balance.confirmed} руб.
      td #{@balance.onlypay_redirect}
      td #{@balance.onlypay_subscribe}
      td #{@balance.onlypay_rebill}
      td #{@balance.onlypay_unsubscribe}

app/views/admin/sellers/edit.html.slim
p
.row
  h3 Редактировать рекламодателя
  = render 'admin/sellers/seller_edit_form' 

app/views/admin/sellers/index.html.slim
h1 Список рекламодателей

= link_to 'Новый рекламодатель', new_admin_seller_path, class: 'button'
- @sellers.each do | seller |
  h2= link_to seller.seller_name, admin_seller_path( seller )

app/views/admin/sellers/new.html.slim
p
.row
  h3 Новый рекламодатель
  = render 'admin/sellers/seller_new_form' 

app/views/admin/sellers/recent_stats.html.slim
= link_to @seller.seller_name, admin_seller_path( @seller ), class: 'button'

.row.large-4.left
  = form_tag( admin_seller_recent_stats_path, method: "get") do
    .large-6.columns
      = label_tag(:start_date, "StartDate")
      = text_field_tag 'start_date', params[ :start_date ] || Time.zone.now.strftime('%d-%m-%Y')
      = button_tag 'Показать', class: 'button'
table
  thead
    tr
      th Час
      th Ожидает начисления
      th Начислено
      th Переходов
      th Подписок
      th Ребиллов
      th Отписок
  tbody
  - @stats.each do | entry | 
    tr
      td= entry[ :hour] 
      td= entry[ :waiting ]
      td= entry[ :confirmed ]
      td= entry[ :onlypay_redirect ]
      td= entry[ :onlypay_subscribe ]
      td= entry[ :onlypay_rebill ]
      td= entry[ :onlypay_unsubscribe ]

javascript:
  $(function() {
    $( "#start_date" ).datepicker( { dateFormat: "dd-mm-yy" } );
  });

app/views/admin/sellers/show.html.slim
h1= @seller.seller_name

h4 Действия
ul.button-group 
  li
    = link_to 'Редактировать', edit_admin_seller_path( @seller ), class: 'button'
  li
    = link_to 'Новое предложение', new_admin_offer_path( seller_id: @seller ), class: 'button'
  li
    = link_to 'Общая статистика', admin_seller_common_stats_path( @seller ), class: 'button'
  li
    = link_to 'Почасовая статистика', admin_seller_recent_stats_path( @seller ), class: 'button'

h4 Кампании
- @offers.each do |offer|
  = link_to offer.name, admin_offer_path( offer ), class: 'button'